# Generated by Django 6.0.2 on 2026-02-17 13:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('ENEM', 'Dissertação ENEM'), ('SIMPLES', 'Dissertação Simples')], default='ENEM', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_corretor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Correcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.IntegerField()),
                ('comentario_geral', models.TextField(blank=True, null=True)),
                ('data_correcao', models.DateTimeField(auto_now_add=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('tipo_erro', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField()),
                ('correcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='app_correcao.correcao')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_competencia', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('correcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_competencias', to='app_correcao.correcao')),
            ],
        ),
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='redacoes/')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Correção'), ('EM_CORRECAO', 'Em Correção'), ('CORRIGIDA', 'Corrigida')], default='AGUARDANDO', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redacoes', to=settings.AUTH_USER_MODEL)),
                ('corretor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcoes_em_andamento', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_correcao.tema')),
            ],
        ),
        migrations.AddField(
            model_name='correcao',
            name='redacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correcao', to='app_correcao.redacao'),
        ),
        migrations.CreateModel(
            name='TextoMotivador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='motivadores/')),
                ('ordem', models.IntegerField(default=0)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivadores', to='app_correcao.tema')),
            ],
        ),
    ]
