# Generated by Django 6.0.2 on 2026-02-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
