# Generated by Django 6.0.2 on 2026-02-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0002_tema_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='redacoes/'),
        ),
    ]
