# Generated by Django 6.0.2 on 2026-02-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0003_redacao_texto_alter_redacao_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.IntegerField()),
                ('contexto', models.CharField(choices=[('GERAL', 'Comentário Geral'), ('PIN', 'Observação do Pin')], max_length=10)),
                ('tipo_erro', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_rapidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta Rápida',
                'verbose_name_plural': 'Respostas Rápidas',
                'ordering': ['competencia', 'titulo'],
            },
        ),
    ]
