# Generated by Django 6.0.2 on 2026-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0004_respostarapida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostarapida',
            options={'ordering': ['modelo', 'competencia', 'titulo'], 'verbose_name': 'Resposta Rápida', 'verbose_name_plural': 'Respostas Rápidas'},
        ),
        migrations.AddField(
            model_name='respostarapida',
            name='modelo',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('SIMPLES', 'Simples')], default='ENEM', max_length=20),
        ),
    ]
