# Generated by Django 6.0.2 on 2026-02-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0005_alter_respostarapida_options_respostarapida_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_limite_enem_minutos', models.IntegerField(default=40, help_text='Tempo máximo para corrigir ENEM')),
                ('tempo_limite_simples_minutos', models.IntegerField(default=25, help_text='Tempo máximo para corrigir redação Simples')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AddField(
            model_name='redacao',
            name='data_inicio_correcao',
            field=models.DateTimeField(blank=True, help_text='Momento exato que o corretor pegou a redação', null=True),
        ),
        migrations.AddField(
            model_name='redacao',
            name='is_urgente',
            field=models.BooleanField(default=False, help_text='Marcado como urgente pelo gestor ou pelo aluno VIP'),
        ),
    ]
