# Generated by Django 6.0.2 on 2026-02-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0006_configuracaosistema_redacao_data_inicio_correcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='vip_pago',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o aluno comprou o pacote de correção rápida'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='is_urgente',
            field=models.BooleanField(default=False, help_text='Marcado como urgente pelo gestor'),
        ),
    ]
