# Generated by Django 6.0.2 on 2026-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0007_redacao_vip_pago_alter_redacao_is_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agencia_conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='minibio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
