# Generated by Django 6.0.2 on 2026-02-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0008_customuser_agencia_conta_customuser_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='valor_bonus_vip',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Bônus extra pago por redações VIP', max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='valor_pagamento_enem',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Valor pago ao corretor por redação ENEM', max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='valor_pagamento_simples',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Valor pago ao corretor por redação Simples', max_digits=10),
        ),
    ]
