# Generated by Django 6.0.2 on 2026-02-22 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0009_configuracaosistema_valor_bonus_vip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostarapida',
            options={},
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('corretor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Saque / Pagamento')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
                ('redacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_correcao.redacao')),
            ],
        ),
    ]
