# Generated by Django 6.0.2 on 2026-02-22 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0010_alter_respostarapida_options_carteira_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: BLACKFRIDAY20', max_length=50, unique=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, help_text='Ex: 20.00 para 20% de desconto', max_digits=5)),
                ('limite_usos', models.IntegerField(default=100, help_text='Quantas vezes esse cupom pode ser usado no total')),
                ('usos_atuais', models.IntegerField(default=0, help_text='Quantas vezes já foi usado')),
                ('ativo', models.BooleanField(default=True)),
                ('data_validade', models.DateTimeField(blank=True, help_text='Se vazio, não expira por data', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pacote Aprovado Medicina', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Ex: 5 Redações ENEM + 1 VIP', null=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço em Reais', max_digits=10)),
                ('qtd_creditos_simples', models.IntegerField(default=0, help_text='Quantas redações normais ele ganha')),
                ('qtd_creditos_vip', models.IntegerField(default=0, help_text='Quantas redações VIP/Urgentes ele ganha')),
                ('ativo', models.BooleanField(default=True, help_text='Se falso, o aluno não vê na loja')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_simples', models.IntegerField(default=0, help_text='Créditos para redações normais')),
                ('saldo_vip', models.IntegerField(default=0, help_text='Créditos para redações urgentes')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
