# Generated by Django 6.0.2 on 2026-02-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0011_cupom_pacote_carteiraaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='custo_creditos_vip',
            field=models.IntegerField(default=2, help_text='Quantos créditos normais custa pedir uma correção VIP'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='preco_avulso_normal',
            field=models.DecimalField(decimal_places=2, default=9.9, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='preco_avulso_vip',
            field=models.DecimalField(decimal_places=2, default=14.9, max_digits=10),
        ),
        migrations.AddField(
            model_name='pacote',
            name='permite_parcelamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='tempo_limite_enem_minutos',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='tempo_limite_simples_minutos',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='valor_bonus_vip',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='valor_pagamento_enem',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='valor_pagamento_simples',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10),
        ),
    ]
