# Generated by Django 6.0.2 on 2026-02-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0012_configuracaosistema_custo_creditos_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='max_parcelas',
            field=models.IntegerField(default=1, help_text='Máximo de parcelas permitidas'),
        ),
    ]
