# Generated by Django 6.0.2 on 2026-02-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0013_pacote_max_parcelas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'verbose_name': 'Configuração do Sistema'},
        ),
        migrations.AddField(
            model_name='pacote',
            name='data_fim_promocao',
            field=models.DateTimeField(blank=True, help_text='Para o cronômetro', null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='destaque_vitrine',
            field=models.BooleanField(default=False, help_text='É uma oferta relâmpago no painel do aluno?'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='texto_vitrine',
            field=models.CharField(blank=True, help_text='Ex: ⚡ Reta Final 50% OFF', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='visivel_loja',
            field=models.BooleanField(default=True, help_text='Aparece na vitrine comum da loja?'),
        ),
        migrations.AlterField(
            model_name='carteiraaluno',
            name='saldo_simples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carteiraaluno',
            name='saldo_vip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='custo_creditos_vip',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='data_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='limite_usos',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='usos_atuais',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='max_parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='qtd_creditos_simples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='qtd_creditos_vip',
            field=models.IntegerField(default=0),
        ),
    ]
