# Generated by Django 6.0.2 on 2026-02-24 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0014_alter_configuracaosistema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='texto_promocional',
            field=models.CharField(blank=True, help_text='Aparecerá na caixa de promoções do aluno', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='compra_unica',
            field=models.BooleanField(default=False, help_text='O aluno só pode comprar este pacote 1 vez na vida?'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='preco_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aparecerá riscado. Ex: De R$ 150 por R$ 99', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_fim_promocao',
            field=models.DateTimeField(blank=True, help_text='Para o cronômetro do pacote', null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço real de venda', max_digits=10),
        ),
        migrations.CreateModel(
            name='BannerVitrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AVISO', 'Aviso (Apenas texto, sem botão de compra)'), ('OFERTA', 'Oferta Relâmpago (Vinculado a um pacote)')], default='OFERTA', max_length=10)),
                ('titulo', models.CharField(help_text='Ex: ⚡ Oferta Relâmpago!', max_length=100)),
                ('descricao', models.CharField(blank=True, help_text='Ex: Pacote VIP com 50% OFF', max_length=200, null=True)),
                ('cor_fundo', models.CharField(default='linear(to-br, orange.400, red.400)', help_text='Código de cor do React', max_length=50)),
                ('data_fim', models.DateTimeField(blank=True, help_text='Quando o cronômetro deve zerar e o banner sumir', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no carrossel')),
                ('pacote_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_correcao.pacote')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_correcao.pacote')),
            ],
        ),
    ]
