# Generated by Django 6.0.2 on 2026-02-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0015_configuracaosistema_texto_promocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='selo_destaque',
            field=models.CharField(blank=True, help_text='Ex: MAIS VENDIDO, RECOMENDADO', max_length=50, null=True),
        ),
    ]
