# Generated by Django 6.0.2 on 2026-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0016_pacote_selo_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannervitrine',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text='Imagem opcional para o fundo', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='tipo',
            field=models.CharField(choices=[('AVISO', 'Aviso (Apenas texto, sem botão de compra)'), ('OFERTA', 'Oferta Relâmpago (Vinculado a um pacote)'), ('EVENTO', 'Evento / Aulão ao Vivo (Calendário)')], default='OFERTA', max_length=10),
        ),
    ]
