# Generated by Django 6.0.2 on 2026-02-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0017_bannervitrine_imagem_fundo_alter_bannervitrine_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannervitrine',
            name='imagem_fundo',
            field=models.TextField(blank=True, help_text='Imagem convertida em Base64', null=True),
        ),
    ]
