# Generated by Django 6.0.2 on 2026-02-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0018_alter_bannervitrine_imagem_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='tempo_carrossel_segundos',
            field=models.IntegerField(default=6, help_text='Tempo em segundos que cada banner fica na tela'),
        ),
    ]
