# Generated by Django 6.0.2 on 2026-02-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0019_configuracaosistema_tempo_carrossel_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experiencias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='formacoes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
