# Generated by Django 6.0.2 on 2026-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0020_customuser_experiencias_customuser_formacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('MANUAIS', 'Manuais e Cartilhas'), ('REPERTORIO', 'Repertório Sociocultural'), ('GRAMATICA', 'Gramática e Estrutura'), ('EXEMPLOS', 'Redações Nota 1000'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('arquivo', models.FileField(upload_to='materiais_apoio/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
