# Generated by Django 6.0.2 on 2026-03-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0021_materialapoio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialapoio',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='materialapoio',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='materialapoio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='materialapoio',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='materialapoio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='materialapoio',
            name='titulo',
        ),
    ]
