# Generated by Django 6.0.2 on 2026-03-01 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0022_remove_materialapoio_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialapoio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='materiais_apoio/'),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='categoria',
            field=models.CharField(choices=[('MANUAIS', 'Manuais e Cartilhas (Alunos)'), ('REPERTORIO', 'Repertório Sociocultural (Alunos)'), ('GRAMATICA', 'Gramática e Estrutura (Alunos)'), ('EXEMPLOS', 'Redações Nota 1000 (Alunos)'), ('MANUAL_CORRETOR', 'Manual do Corretor (Professores)'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=200),
            preserve_default=False,
        ),
    ]
