# Generated by Django 6.0.2 on 2026-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0023_materialapoio_arquivo_materialapoio_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialapoio',
            name='categoria',
            field=models.CharField(choices=[('ALUNO_MANUAL', 'Manuais e Cartilhas'), ('ALUNO_REPERTORIO', 'Repertório Sociocultural'), ('ALUNO_GRAMATICA', 'Gramática e Estrutura'), ('ALUNO_EXEMPLOS', 'Redações Nota 1000'), ('CORRETOR_CARTILHA', 'Cartilha Oficial (MEC/Banca)'), ('CORRETOR_REGUA', 'Régua de Penalizações'), ('CORRETOR_DESVIOS', 'Guia de Desvios (Gramática)'), ('CORRETOR_REPERTORIO', 'Guia de Repertórios Aceitos'), ('CORRETOR_COMUNICADO', 'Comunicados de Alinhamento')], max_length=30),
        ),
    ]
