# Generated by Django 6.0.2 on 2026-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0024_alter_materialapoio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialapoio',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
