# Generated by Django 6.0.2 on 2026-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0025_materialapoio_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialapoio',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
