# Generated by Django 6.0.2 on 2026-03-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0026_materialapoio_dados_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='corretor',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='redacao',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='pagamento_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='qtd_simples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transacao',
            name='qtd_vip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado / Expirado')], default='PENDENTE', max_length=20),
        ),
    ]
