# Generated by Django 6.0.2 on 2026-08-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0027_rename_corretor_transacao_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='qtd_normal_pendente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carteira',
            name='qtd_vip_pendente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carteira',
            name='saque_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PagamentoCorretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_normal', models.IntegerField(default=0)),
                ('qtd_vip', models.IntegerField(default=0)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
