# Generated by Django 6.0.2 on 2026-08-16 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0028_carteira_qtd_normal_pendente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='cnpj_plataforma',
            field=models.CharField(default='00.000.000/0001-00', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='razao_social_plataforma',
            field=models.CharField(default='Guia do Texto Plataforma Educacional', max_length=255),
        ),
        migrations.AddField(
            model_name='pagamentocorretor',
            name='arquivo_recibo',
            field=models.FileField(blank=True, null=True, upload_to='recibos_assinados/'),
        ),
        migrations.AddField(
            model_name='pagamentocorretor',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 16, 16, 12, 31, 191510, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamentocorretor',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentocorretor',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_RECIBO', 'Aguardando Recibo Assinado'), ('EM_ANALISE', 'Em Análise pelo Financeiro'), ('PAGO', 'Pagamento Efetuado'), ('RECUSADO', 'Recibo Recusado')], default='AGUARDANDO_RECIBO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagamentocorretor',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
