# Generated by Django 6.0.2 on 2026-09-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0029_configuracaosistema_cnpj_plataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_coordenador',
            field=models.BooleanField(default=False, help_text='Acesso à Torre de Controle e Gestão de Corretores'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_financeiro',
            field=models.BooleanField(default=False, help_text='Acesso ao Painel Financeiro e E-commerce'),
        ),
    ]
