# Generated by Django 6.0.2 on 2026-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0030_customuser_foto_perfil_customuser_is_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correcao',
            name='avaliacao_aluno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='correcao',
            name='comentario_avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
