# Generated by Django 6.0.2 on 2026-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0031_correcao_avaliacao_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocorretor',
            name='data_prevista_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
