# Generated by Django 6.0.2 on 2026-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0032_pagamentocorretor_data_prevista_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannervitrine',
            name='cor_fundo',
            field=models.CharField(default='linear(to-br, orange.400, red.400)', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='imagem_fundo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='tipo',
            field=models.CharField(choices=[('AVISO', 'Aviso'), ('OFERTA', 'Oferta Relâmpago'), ('EVENTO', 'Evento / Aulão')], default='OFERTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='bannervitrine',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correcao',
            name='nota_final',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materialapoio',
            name='categoria',
            field=models.CharField(choices=[('ALUNO_MANUAL', 'Manuais e Cartilhas'), ('ALUNO_REPERTORIO', 'Repertório Sociocultural'), ('ALUNO_GRAMATICA', 'Gramática e Estrutura'), ('ALUNO_EXEMPLOS', 'Redações Nota 1000'), ('CORRETOR_CARTILHA', 'Cartilha Oficial'), ('CORRETOR_REGUA', 'Régua de Penalizações'), ('CORRETOR_DESVIOS', 'Guia de Desvios'), ('CORRETOR_REPERTORIO', 'Guia de Repertórios Aceitos'), ('CORRETOR_COMUNICADO', 'Comunicados Rápidos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notacompetencia',
            name='nota',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='compra_unica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_fim_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='destaque_vitrine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='preco_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='selo_destaque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='texto_vitrine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='visivel_loja',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='respostarapida',
            name='modelo',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('PADRAO_100', 'Padrão 100 pts'), ('PADRAO_10', 'Padrão 10 pts'), ('SIMPLES', 'Simples')], default='ENEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tipo',
            field=models.CharField(choices=[('ENEM', 'Dissertação ENEM'), ('PADRAO_100', 'Padrão 100 pts'), ('PADRAO_10', 'Padrão 10 pts'), ('SIMPLES', 'Simples (Legado)')], default='ENEM', max_length=15),
        ),
    ]
