# Generated by Django 6.0.2 on 2026-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0033_alter_bannervitrine_cor_fundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannervitrine',
            name='cor_pelicula',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='bannervitrine',
            name='link_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannervitrine',
            name='opacidade_pelicula',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='bannervitrine',
            name='texto_botao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
