# Generated by Django 6.0.2 on 2026-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0034_bannervitrine_cor_pelicula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GabaritoPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.IntegerField(help_text='0 para OUTROS, 1 a 5 para as competências')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
    ]
