# Generated by Django 6.0.2 on 2026-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0035_gabaritopin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabaritopin',
            name='tipo',
            field=models.CharField(choices=[('ERRO', 'Erro/Desvio'), ('ELOGIO', 'Elogio/Destaque')], default='ERRO', max_length=10),
        ),
    ]
